name: Deploy Pulse.Server

on:
  workflow_dispatch
    
jobs:
  build_and_deploy:
    environment: main
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./Pulse.Server

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install MAUI Android
      run: dotnet workload restore
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish --no-restore --configuration Release
    - name: Copy files to server
      uses: easingthemes/ssh-deploy@v2.2.11
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        SOURCE: "Pulse.Server/bin/Release/net6.0/publish/"
        TARGET: Pulse.Server
        REMOTE_HOST: ${{ secrets.SERVER_HOST }}
        REMOTE_USER: ${{ secrets.SERVER_USER }}
    - name: Run the app as a service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          sudo cp Pulse.Server/pulse.service /etc/systemd/system/pulse.service
          sudo systemctl daemon-reload
          sudo systemctl restart pulse
    
    
